spring.application.name=Digital Wallet System
spring.datasource.url=jdbc:h2:mem:walletdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=dws
spring.datasource.password=dws
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

server.port=8080
